import { HeadshotStyle } from './types';

export const HEADSHOT_STYLES: HeadshotStyle[] = [
  {
    id: 'corporate-grey',
    name: 'Corporate Grey',
    prompt: 'Generate a professional corporate headshot of a person against a solid, textured grey backdrop. The lighting should be soft and even, highlighting facial features clearly. The person should be wearing professional business attire, like a dark suit jacket and a light-colored dress shirt or blouse. The expression should be confident and friendly.',
    previewUrl: 'https://picsum.photos/seed/corporate/300/300',
  },
  {
    id: 'black-and-white',
    name: 'Classic B&W',
    prompt: 'Generate a dramatic and classic black and white professional headshot. The lighting should be high-contrast (chiaroscuro), creating depth and character. The background should be dark and simple. The focus should be entirely on the person\'s expression, which should be thoughtful and strong. The attire should be simple and dark.',
    previewUrl: 'https://picsum.photos/seed/bw/300/300',
  },
  {
    id: 'minimalist-white',
    name: 'Minimalist White',
    prompt: 'Generate a clean and modern professional headshot of a person against a pure white background. The lighting should be very bright and shadowless, creating a high-key effect. The attire should be simple and elegant. The overall feel should be minimalist, fresh, and sophisticated.',
    previewUrl: 'https://picsum.photos/seed/minimalist/300/300',
  },
  {
    id: 'engraved-ink',
    name: 'Engraved Ink',
    prompt: 'Generate a striking, high-contrast, black and white headshot in an engraved or woodcut illustration style. The image should be composed of fine, detailed black lines on a light, off-white background, creating a sense of texture and depth. The lighting should be dramatic, casting strong shadows to emphasize facial features. The overall mood should be artistic, intense, and sophisticated, resembling a classic ink portrait.',
    previewUrl: 'https://picsum.photos/seed/engraved/300/300',
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    prompt: 'Generate a headshot with a vintage film aesthetic. The image should have warm, slightly desaturated tones, soft focus, and a subtle film grain. The lighting should be natural and gentle, reminiscent of classic 1970s portrait photography. The attire and background should be simple to keep the focus on the person\'s timeless and nostalgic expression.',
    previewUrl: 'https://picsum.photos/seed/vintage/300/300',
  },
  {
    id: 'futuristic-neon',
    name: 'Futuristic Neon',
    prompt: 'Generate a futuristic, high-fashion headshot bathed in neon light. The background should be dark, with vibrant streaks of electric blue, pink, and purple light creating a cyberpunk feel. The person should have a modern, edgy look, with attire that is sleek and stylish. The expression should be confident and intense, fitting the dynamic, high-tech mood.',
    previewUrl: 'https://picsum.photos/seed/futuristic/300/300',
  },
  {
    id: 'gothic-noir',
    name: 'Gothic Noir',
    prompt: 'Generate a dramatic, atmospheric headshot in a gothic noir style. The image should be in high-contrast black and white, with deep shadows and selective highlights (chiaroscuro). The background should be dark and mysterious, perhaps suggesting a Victorian or moody urban setting. The expression should be intense and enigmatic.',
    previewUrl: 'https://picsum.photos/seed/gothic/300/300',
  },
  {
    id: 'cyberpunk-hacker',
    name: 'Cyberpunk Hacker',
    prompt: 'Generate a headshot in a cyberpunk aesthetic. The person should be illuminated by holographic data displays and neon city lights in shades of magenta, cyan, and electric blue. The background should be a dark, futuristic cityscape at night. The attire should be tech-infused, and the expression should be focused and cool, as if they are interfacing with a high-tech system.',
    previewUrl: 'https://picsum.photos/seed/cyberpunk/300/300',
  },
  {
    id: 'golden-hour-glow',
    name: 'Golden Hour',
    prompt: 'Generate a professional headshot with a warm, golden hour lighting effect. The background should be a simple outdoor or office setting with soft, diffused light. The person should look approachable and confident, with a gentle smile. Attire should be smart-casual.',
    previewUrl: 'https://picsum.photos/seed/golden/300/300',
  },
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    prompt: 'Generate a modern headshot suitable for a tech professional. The background should be a contemporary office with blurred elements like glass walls or subtle branding. The person should be wearing stylish, smart-casual clothing. The lighting should be clean and bright, and the expression confident and forward-looking.',
    previewUrl: 'https://picsum.photos/seed/tech/300/300',
  },
  {
    id: 'academic-portrait',
    name: 'Academic',
    prompt: 'Generate a classic academic-style headshot. The background should feature a bookshelf, a study, or a university campus setting, subtly out of focus. The person should have a thoughtful and intelligent expression. Attire should be professional and slightly formal, like a blazer or a smart sweater.',
    previewUrl: 'https://picsum.photos/seed/academic/300/300',
  },
  {
    id: 'creative-professional',
    name: 'Creative',
    prompt: 'Generate an artistic headshot for a creative professional. The background could be an exposed brick wall, a minimalist art studio, or a textured, solid color. The lighting should be more dramatic, perhaps with a single key light to create interesting shadows. The expression should be unique and show personality.',
    previewUrl: 'https://picsum.photos/seed/creative/300/300',
  },
  {
    id: 'outdoor-natural',
    name: 'Outdoor Natural',
    prompt: 'Generate a friendly and professional headshot taken outdoors. The background should be a pleasant, natural setting like a park or garden, with soft, natural daylight. The person should have a relaxed and authentic smile. The attire should be business casual, appropriate for a less formal professional context.',
    previewUrl: 'https://picsum.photos/seed/outdoor/300/300',
  },
  {
    id: 'monochromatic-pop',
    name: 'Color Pop',
    prompt: 'Generate a vibrant, modern headshot with a monochromatic color scheme. The background should be a bold, solid color (e.g., teal, mustard yellow, or deep blue). The person\'s attire should complement the background color. The lighting should be clean and even, making the subject pop. The expression should be confident and energetic.',
    previewUrl: 'https://picsum.photos/seed/colorpop/300/300',
  },
  {
    id: 'watercolor-portrait',
    name: 'Watercolor',
    prompt: 'Generate a professional headshot in a beautiful, artistic watercolor style. The image should have soft, blended colors and visible brushstroke textures. The background should be a light, abstract watercolor wash. The person\'s features should be recognizable but rendered with an artistic, painterly quality. The overall mood should be creative, elegant, and unique.',
    previewUrl: 'https://picsum.photos/seed/watercolor/300/300',
  },
  {
    id: 'ceo-power-shot',
    name: 'CEO Power',
    prompt: 'Generate a powerful and confident CEO-style headshot. The person should be wearing sharp, high-end business attire. The lighting should be crisp and professional, creating a strong, defined look. The background should be a modern, out-of-focus executive office or a panoramic city view from a high-rise window. The expression should be commanding yet approachable.',
    previewUrl: 'https://picsum.photos/seed/ceo/300/300',
  },
  {
    id: 'linkedin-blue-bg',
    name: 'LinkedIn Blue',
    prompt: 'Generate a clean, professional headshot perfect for a LinkedIn profile. The background should be a smooth gradient of professional blues, similar to the classic LinkedIn aesthetic. The lighting on the person should be bright and even. The attire should be business casual, and the expression should be friendly, confident, and engaging.',
    previewUrl: 'https://picsum.photos/seed/linkedin/300/300',
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial',
    prompt: 'Generate a high-fashion, editorial-style headshot suitable for a magazine cover. The lighting should be dramatic and stylized, creating a bold, eye-catching effect. The pose and expression should be confident and unconventional. The background should be simple but stylish, allowing the person to be the complete focus. The overall look should be chic, modern, and polished.',
    previewUrl: 'https://picsum.photos/seed/editorial/300/300',
  },
  {
    id: 'soft-approachable',
    name: 'Soft Light',
    prompt: 'Generate a headshot that feels warm, soft, and approachable. Use diffuse, natural-looking light to create a gentle and flattering effect with minimal shadows. The background should be light-colored and softly blurred. The person should have a genuine, friendly smile. The attire should be casual yet neat. The overall mood should be inviting and authentic.',
    previewUrl: 'https://picsum.photos/seed/soft/300/300',
  },
  {
    id: 'dramatic-spotlight',
    name: 'Spotlight',
    prompt: 'Generate a highly dramatic headshot with a single spotlight illuminating the person\'s face against a pure black background. The lighting should create strong highlights and deep shadows, sculpting the facial features. The focus should be entirely on the person\'s intense and captivating expression. This style is bold, theatrical, and memorable.',
    previewUrl: 'https://picsum.photos/seed/spotlight/300/300',
  },
  {
    id: 'urban-poster-art',
    name: 'Urban Poster Art',
    prompt: 'A striking, high-contrast, black and white headshot in an urban poster art style with bold red graphic accents. The overall mood should be artistic and modern. Include the hashtag "#{{username}}" prominently in the design.',
    previewUrl: 'https://picsum.photos/seed/urbanposter/300/300',
    userInput: {
      label: 'Username for Hashtag',
      placeholder: 'e.g., your_handle',
    },
  },
  {
    id: 'construction-spotlight',
    name: 'Construction Spotlight',
    prompt: 'Generate an aesthetic 0.6 lens portrait of the person. They are standing, leaning against a wall inside a construction building, illuminated by a single dramatic spotlight. The person is wearing a blue denim jacket, black jeans, and classy sunglasses, with their hands in their jeans pockets. The lighting should be moody and high-contrast, creating a cinematic, nightmare-like atmosphere.',
    previewUrl: 'https://picsum.photos/seed/construction/300/300',
  },
];