
import { GoogleGenAI, Modality, GenerateContentResponse } from '@google/genai';

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const imageEditModel = 'gemini-2.5-flash-image';
const chatModel = 'gemini-2.5-flash';

interface ImageInput {
  mimeType: string;
  data: string; // base64 encoded string
}

export const generateHeadshot = async (
  image: ImageInput,
  prompt: string
): Promise<string> => {
  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: imageEditModel,
      contents: {
        parts: [
          {
            inlineData: {
              data: image.data,
              mimeType: image.mimeType,
            },
          },
          {
            text: `Based on the person in this image, ${prompt}`,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const mimeType = part.inlineData.mimeType;
        return `data:${mimeType};base64,${base64ImageBytes}`;
      }
    }
    throw new Error('No image was generated by the API.');
  } catch (error) {
    console.error('Error generating headshot:', error);
    throw new Error('Failed to generate headshot. Please try again.');
  }
};


export const getChatResponse = async (prompt: string): Promise<string> => {
  try {
     const response = await ai.models.generateContent({
       model: chatModel,
       contents: prompt
     });
     return response.text;
  } catch (error) {
    console.error('Error getting chat response:', error);
    throw new Error('Failed to get a response from the chatbot. Please check the console for details.');
  }
};
